### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Denisov21** [Brackets-Themes/VisualStudio#1]
I saw that you are creating many new topics in this way, are used for the integration of themes directly in Brackets?

**Comment by MiguelCastillo** [comment]
Yup, brackets will be having core support for themes.  They will managed as extensions :)

**Comment by MiguelCastillo** [comment]
I am hoping you are going to create your own themes and put them up in here!

**Comment by Denisov21** [comment]
Yes I will create my theme! When there will be native support of the themes Brackets?

**Comment by MiguelCastillo** [comment]
I am not sure quite yet.  But we are working hard to make it happen in the next couple of sprints.

**Comment by MiguelCastillo** [comment]
This is the pull request for it https://github.com/adobe/brackets/pull/7616

**Comment by Denisov21** [comment]
Can I take a theme already done and modify it?

**Comment by MiguelCastillo** [comment]
All themes are open source with MIT... So yeah you can definitely do that. :)
