### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Denisov21** [Brackets-Themes/VisualStudio#2]
Hi, @MiguelCastillo 
I have created a new theme for the future Theme Editor inside Brackets that you are implementing. Could you tell me if everything is okay? The file earth.css is what you've already joined in Themes. Thanks in advance!!

**Comment by MiguelCastillo** [comment]
@Denisov21 Hey how is it going?  Let me take a look and give you feedback.  I see that you have created a couple of themes and have submitted them to the Themes extension.  Thank you so much!  It might also be a good idea to make those themes actual themes extensions and put them up in here https://github.com/Brackets-Themes. :)

**Comment by Denisov21** [comment]
Well. My problem is that I do not know how to copy it https://github.com/Brackets-Themes.! I am a beginner in git!

**Comment by MiguelCastillo** [comment]
@Denisov21 Hi!  I have added some instruction to https://github.com/Brackets-Themes/BoilerPlate so that you can get started on making your own themes!  Please help me improve it by giving me feedback :)

I still need to figure a workflow for allowing people to add their themes here.  But for now having your own repo should be ok to get you started

**Comment by Denisov21** [comment]
The guide is well done ... but I'd like to add a tab management extensions "Themes" next to "Install" in which all the new themes extensions they were here. The name of the tab "Themes"

![senza nome](https://cloud.githubusercontent.com/assets/2547815/3530481/e9616108-07a4-11e4-8d48-555618b10f05.png)

**Comment by MiguelCastillo** [comment]
@Denisov21 Yeah, thats awesome feedback about adding the themes tab.  We want to do that, but I am not sure we can do it for this release.  Why don't you voice this exact same thing in here https://github.com/adobe/brackets/pull/8302?

**Comment by Denisov21** [comment]
Hi @MiguelCastillo Ok, done!

**Comment by MiguelCastillo** [comment]
Cool :)

**Comment by MiguelCastillo** [comment]
@Denisov21 Have you been had any luck setting up the branch and install themes from git as extensions yet?

I can help you with your first theme extension if you are having problems.  Would you be interested in helping with Brackets-Themes organization?

**Comment by Denisov21** [comment]
Hi @MiguelCastillo 

a) Honestly I have not tried it yet!
b) I created my first theme as an extension. I do not think I have any problems, but if you give me a look, I'm glad. (https://github.com/Denisov21/EarthThemeForBrackets)
I decided to create this issue because at work I have no problem staying long hours in front of the PC with the highlights (see image). So I decided to create this theme.

![immagine 001 14072014](https://cloud.githubusercontent.com/assets/2547815/3574236/e4155508-0b7b-11e4-979a-36b529d63e00.png)

Question: my theme was not able to solve a problem. How do I change this color (red arrow)?

P.S. Install this extension (https://github.com/thaneuk/brackets-special-html-chars)

![senza nome](https://cloud.githubusercontent.com/assets/2547815/3574391/9640e6b0-0b7d-11e4-9e26-9bd3a2eea429.png)

**Comment by MiguelCastillo** [comment]
@Denisov21 I don't have that extension installed, but as long as it is in the HTML of bracket you can certainly customize it.  I always use chrome developer tools to inspect the DOM to choose a suitable class to apply your css magic.
